### ISSUE TITLE
libgtk - attempt to unlock mutex that was not locked

### ISSUE THREAD

**Issue by atkinsam** [smistad/SIPL#32]
Programs compiled using the latest version of SIPL and libgtk2.0-dev version 2.24.30 crash during execution with error
`Attempt to unlock mutex that was not locked`

From what I've read elsewhere this is because of an update in libgtk. Just thought I'd let you know. Thanks for your work on this and making it open source.

**Comment by smistad** [comment]
I noticed this bug as well a couple of days ago. It should be fixed in this commit https://github.com/smistad/SIPL/commit/7e10fa932b56718218604ce6f3d75a44456ac181 in the beta-0.4 branch. Thanks for reporting.
