### ISSUE TITLE
Is GTK required?

### ISSUE THREAD

**Issue by jtaylorme** [smistad/SIPL#34]
I notice in the code there is an option to "USE_GTK", is it required.    Instructions say to install it but looks like it might not be required.

This probably wasn't an "Issue" but wasn't sure where to ask this question.

Thanks.

Jim

**Comment by smistad** [comment]
Firstly note that this library is not maintained anymore. It is over 8 years old. But to answer your question, yes GTK seems to be optional, see the sipl_use_gtk cmake option https://github.com/smistad/SIPL/blob/6a3b6d05388389afd0292e9dd86d5e3b85bca109/CMakeLists.txt#L17

**Comment by jtaylorme** [comment]
I did.   Was actually surprised to get a response but we often have not because we ask not :-)    

I thought so but was having trouble with the compile and wanted to make sure so I wasn't wasting time trying it without.

Thanks.   Appreciate the reply.
